apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: back-pod
      labels:
        app: back-app
    spec:
      containers:
      - image: cry20011/pdris-back
        name: backend
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent