apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: front-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: front-pod
      labels:
        app: front-app
    spec:
      containers:
      - image: cry20011/pdris-front
        name: frontend
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent